"""create_users

Revision ID: c709541309d5
Revises: ffdc0a98111c
Create Date: 2021-03-04 10:43:28.005326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c709541309d5'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    op.create_table('rides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('startTime', sa.DateTime(), nullable=False),
    sa.Column('endTime', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(precision=8), nullable=False),
    sa.Column('longitude', sa.Float(precision=8), nullable=False),
    sa.Column('isLocal', sa.Boolean(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('rideId', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rideId'], ['rides.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_committed_rides',
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('rideId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rideId'], ['rides.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], )
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postId', sa.Integer(), nullable=True),
    sa.Column('imageUrl', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['postId'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('city', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('level', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('profileImageUrl', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'state')
    op.drop_column('users', 'profileImageUrl')
    op.drop_column('users', 'level')
    op.drop_column('users', 'city')
    op.drop_table('images')
    op.drop_table('users_committed_rides')
    op.drop_table('posts')
    op.drop_table('rides')
    op.drop_table('follows')
    # ### end Alembic commands ###
